### ISSUE TITLE
socket.inc is out of date

### ISSUE THREAD

**Issue by SteveBox0** [JoinedSenses/SourceMod-IncludeLibrary#6]
`error 139: could not find type "Socket"`

Newer version at https://github.com/JoinedSenses/sm-ext-socket/tree/master/scripting/include

**Comment by JoinedSenses** [comment]
The file here intentionally does not have Socket methodmap. This is because that repo contains an updated inc and a rebuilt extension. That inc will not work with people still using the original extension.

When someone gets the extension from that fork, they should also be getting the include.
